//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace covid19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUOCGIA
    {
        public string MAQG { get; set; }
        public string TENQG { get; set; }
    
        public virtual THONGKEQG THONGKEQG { get; set; }
    }
}
