//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace covid19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGKEQGBYDAY
    {
        public decimal STT { get; set; }
        public string MAQG { get; set; }
        public string TINH { get; set; }
        public string THANHPHO { get; set; }
        public Nullable<decimal> SOCAMAC { get; set; }
        public Nullable<decimal> SOCACHET { get; set; }
        public Nullable<decimal> SOCAKHOI { get; set; }
        public Nullable<System.DateTime> NGAYGHINHAN { get; set; }
    }
}
