//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace covid19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGKEQG
    {
        public string MAQG { get; set; }
        public Nullable<decimal> TONGSOCAMAC { get; set; }
        public Nullable<decimal> TONGSOCACHET { get; set; }
        public Nullable<decimal> TONGSOCAKHOI { get; set; }
    
        public virtual QUOCGIA QUOCGIA { get; set; }
    }
}
